class_name SaveError
extends RefCounted

const OK := 0
const UNKNOWN := 1
const INVALID_ARGUMENT := 2
const FILE_NOT_FOUND := 3
const DIR_CREATE_FAILED := 4
const READ_FAILED := 5
const WRITE_FAILED := 6
const DELETE_FAILED := 7
const COPY_FAILED := 8
const RENAME_FAILED := 9
const INVALID_FORMAT := 10
const SERIALIZE_FAILED := 11
const DESERIALIZE_FAILED := 12
const SLOT_ALREADY_EXISTS := 13
const SLOT_NOT_FOUND := 14
const INDEX_READ_FAILED := 15
const INDEX_WRITE_FAILED := 16
const VERSION_MISMATCH := 17
const MIGRATION_REQUIRED := 18
const MIGRATION_FAILED := 19
const ENCRYPTION_FAILED := 20
const COMPRESSION_FAILED := 21
const BACKUP_RESTORE_FAILED := 22
const INVALID_SAVEABLE := 23
const DUPLICATE_SAVE_KEY := 24
const PIPELINE_CANCELLED := 25
